export const CRAFT_TRADES = [
  'Air Balance Technician',
  'Alarm Installer (see also Electrician)',
  'Boilermaker',
  'Bricklayer (can also include tile setter, terrazzo workers and marble masons)',
  'Carpenter (can also include cement masons, floor coverer, millwright and pile driver (non-equipment), plasterers and terrazzo workers)',
  'Electrician (includes communication technician, line, neon sign and wireman; can also include alarm installer)',
  'Elevator Constructor',
  'Glazier (see also Painters and Allied Trades)',
  'Hod Carrier (see also Laborers) (includes brick-mason tender and plaster tender)',
  'Iron Worker (can also include fence erectors (steel/iron))',
  'Laborer (includes asbestos abatement, fence erector (non-steel/iron), flag person, highway striping and traffic barrier erector; can also include cement masons, hod carrier, brick mason tender and plaster tender)',
  'Lubrication and Service Engineer',
  'Mason (can also include cement mason, plasterer, tile setter, terrazzo workers and marble masons)',
  'Millwright (see also carpenter)',
  'Operating Engineer (can also include equipment greaser, piledriver, soils and material tester, steel fabricator/erector (without equipment), surveyor (non-licensed) and well driller)',
  'Painters and Allied Trades (can also include glaziers, floor coverers and tapers)',
  'Plumber/Pipefitter',
  'Refrigeration',
  'Roofer (not sheet metal)',
  'Sheet Metal Worker (can also include air balance technician)',
  'Sprinkler Fitter',
  'Truck Driver',
  'Well Driller (see also Operating Engineer)',
] as const
